{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "1b8170db",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cryptocurrency Wallet\n",
    "################################################################################\n",
    "\n",
    "# This file contains the Ethereum transaction functions that you have created throughout this module’s lessons. By using import statements, you will integrate this `crypto_wallet.py` Python script into the Fintech Finder interface program that is found in the `fintech_finder.py` file.\n",
    "\n",
    "################################################################################\n",
    "# Imports\n",
    "import os\n",
    "import requests\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "from bip44 import Wallet\n",
    "from web3 import Account\n",
    "from web3 import middleware\n",
    "from web3.gas_strategies.time_based import medium_gas_price_strategy\n",
    "\n",
    "################################################################################\n",
    "# Wallet functionality\n",
    "\n",
    "def generate_account():\n",
    "    \"\"\"Create a digital wallet and Ethereum account from a mnemonic seed phrase.\"\"\"\n",
    "    # Fetch mnemonic from environment variable.\n",
    "    mnemonic = os.getenv(\"MNEMONIC\")\n",
    "\n",
    "    # Create Wallet Object\n",
    "    wallet = Wallet(mnemonic)\n",
    "\n",
    "    # Derive Ethereum Private Key\n",
    "    private, public = wallet.derive_account(\"eth\")\n",
    "\n",
    "    # Convert private key into an Ethereum account\n",
    "    account = Account.privateKeyToAccount(private)\n",
    "\n",
    "    return account\n",
    "\n",
    "def get_balance(w3, address):\n",
    "    \"\"\"Using an Ethereum account address access the balance of Ether\"\"\"\n",
    "    # Get balance of address in Wei\n",
    "    wei_balance = w3.eth.get_balance(address)\n",
    "\n",
    "    # Convert Wei value to ether\n",
    "    ether = w3.fromWei(wei_balance, \"ether\")\n",
    "\n",
    "    # Return the value in ether\n",
    "    return ether# Cryptocurrency Wallet\n",
    "\n",
    "# Imports\n",
    "import streamlit as st\n",
    "from dataclasses import dataclass\n",
    "from typing import Any, List\n",
    "from web3 import Web3\n",
    "\n",
    "w3 = Web3(Web3.HTTPProvider('HTTP://127.0.0.1:7545'))\n",
    "\n",
    "# From `crypto_wallet.py import the functions generate_account, get_balance,\n",
    "#  and send_transaction\n",
    "from crypto_wallet import generate_account, get_balance, send_transaction\n",
    "\n",
    "# Fintech Finder Candidate Information\n",
    "\n",
    "# Database of Fintech Finder candidates including their name, digital address, rating and hourly cost per Ether.\n",
    "# A single Ether is currently valued at $1,500\n",
    "candidate_database = {\n",
    "    \"Lane\": [\"Lane\", \"0xaC8eB8B2ed5C4a0fC41a84Ee4950F417f67029F0\", \"4.3\", .20, \"Images/lane.jpeg\"],\n",
    "    \"Ash\": [\"Ash\", \"0x2422858F9C4480c2724A309D58Ffd7Ac8bF65396\", \"5.0\", .33, \"Images/ash.jpeg\"],\n",
    "    \"Jo\": [\"Jo\", \"0x8fD00f170FDf3772C5ebdCD90bF257316c69BA45\", \"4.7\", .19, \"Images/jo.jpeg\"],\n",
    "    \"Kendall\": [\"Kendall\", \"0x8fD00f170FDf3772C5ebdCD90bF257316c69BA45\", \"4.1\", .16, \"Images/kendall.jpeg\"]\n",
    "}\n",
    "\n",
    "# A list of the FinTech Finder candidates first names\n",
    "people = [\"Lane\", \"Ash\", \"Jo\", \"Kendall\"]\n",
    "\n",
    "\n",
    "def get_people():\n",
    "    \"\"\"Display the database of Fintech Finders candidate information.\"\"\"\n",
    "    db_list = list(candidate_database.values())\n",
    "\n",
    "    for number in range(len(people)):\n",
    "        st.image(db_list[number][4], width=200)\n",
    "        st.write(\"Name: \", db_list[number][0])\n",
    "        st.write(\"Ethereum Account Address: \", db_list[number][1])\n",
    "        st.write(\"FinTech Finder Rating: \", db_list[number][2])\n",
    "        st.write(\"Hourly Rate per Ether: \", db_list[number][3], \"eth\")\n",
    "        st.text(\" \\n\")\n",
    "\n",
    "\n",
    "# Streamlit Code\n",
    "\n",
    "# Streamlit application headings\n",
    "st.markdown(\"# Fintech Finder!\")\n",
    "st.markdown(\"## Hire A Fintech Professional!\")\n",
    "st.text(\" \\n\")\n",
    "\n",
    "\n",
    "# Streamlit Sidebar Code - Start\n",
    "st.sidebar.markdown(\"## Client Account Address and Ethernet Balance in Ether\")\n",
    "\n",
    "\n",
    "# Write the client's Ethereum account address to the sidebar\n",
    "st.sidebar.write(account.address)\n",
    "\n",
    "# Call `get_balance` function and pass it your account address\n",
    "# Write the returned ether balance to the sidebar\n",
    "st.sidebar.write(\"Ethereum Account:\", get_balance(w3, account.address))\n",
    "\n",
    "# Create a select box to chose a FinTech Hire candidate\n",
    "person = st.sidebar.selectbox('Select a Person', people)\n",
    "\n",
    "# Create a input field to record the number of hours the candidate worked\n",
    "hours = st.sidebar.number_input(\"Number of Hours\")\n",
    "\n",
    "st.sidebar.markdown(\"## Candidate Name, Hourly Rate, and Ethereum Address\")\n",
    "\n",
    "# Identify the FinTech Hire candidate\n",
    "candidate = candidate_database[person][0]\n",
    "\n",
    "# Write the Fintech Finder candidate's name to the sidebar\n",
    "st.sidebar.write(candidate)\n",
    "\n",
    "# Identify the FinTech Finder candidate's hourly rate\n",
    "hourly_rate = candidate_database[person][3]\n",
    "\n",
    "# Write the inTech Finder candidate's hourly rate to the sidebar\n",
    "st.sidebar.write(hourly_rate)\n",
    "\n",
    "# Identify the FinTech Finder candidate's Ethereum Address\n",
    "candidate_address = candidate_database[person][1]\n",
    "\n",
    "# Write the inTech Finder candidate's Ethereum Address to the sidebar\n",
    "st.sidebar.write(candidate_address)\n",
    "\n",
    "# Write the Fintech Finder candidate's name to the sidebar\n",
    "\n",
    "st.sidebar.markdown(\"## Total Wage in Ether\")\n",
    "\n",
    "# Write the `wage` calculation to the Streamlit sidebar\n",
    "st.sidebar.write(\"Wage: \", wage)\n",
    "\n",
    "if st.sidebar.button(\"Send Transaction\"):\n",
    "\n",
    "    # Call the `send_transaction` function and pass it 3 parameters:\n",
    "    # Your `account`, the `candidate_address`, and the `wage` as parameters\n",
    "    # Save the returned transaction hash as a variable named `transaction_hash`\n",
    "    transaction_hash = send_transaction(w3,account=account,to=candidate_address,wage=wage)\n",
    "\n",
    "    # Markdown for the transaction hash\n",
    "    st.sidebar.markdown(\"#### Validated Transaction Hash\")\n",
    "\n",
    "    # Write the returned transaction hash to the screen\n",
    "    st.sidebar.write(transaction_hash)\n",
    "\n",
    "    # Celebrate your successful payment\n",
    "    st.balloons()\n",
    "\n",
    "# Step 3: Inspect the Transaction\n",
    "\n",
    "# Send a test transaction by using the application’s web interface, and then\n",
    "# look up the resulting transaction hash in Ganache.\n",
    "\n",
    "# Complete the following steps:\n",
    "\n",
    "# 1. From your terminal, navigate to the project folder that contains\n",
    "# your `.env` file and the `fintech_finder.py` and `crypto_wallet.py` files.\n",
    "# Be sure to activate your Conda `dev` environment if it is not already active.\n",
    "\n",
    "# 2. To launch the Streamlit application,\n",
    "# type `streamlit run fintech_finder.py`.\n",
    "\n",
    "# 3. On the resulting webpage, select a candidate that you would like to hire\n",
    "# from the appropriate drop-down menu. Then, enter the number of hours that you\n",
    "# would like to hire them for. (Remember, you do not have a lot of ether in\n",
    "# your account, so you cannot hire them for long!)\n",
    "\n",
    "# 4 Click the Send Transaction button to sign and send the transaction with\n",
    "# your Ethereum account information. If the transaction is successfully\n",
    "# communicated to Ganache, validated, and added to a block,\n",
    "# a resulting transaction hash code will be written to the Streamlit\n",
    "# application sidebar.\n",
    "    \n",
    "# 5. Navigate to the Ganache accounts tab and locate your account (index 0).\n",
    "    # * Take a screenshot of the address, balance, and transaction (TX) count.\n",
    "    # Save this screenshot to the README.md file of your GitHub repository for\n",
    "    #  this Challenge assignment.\n",
    "    \n",
    "# 6. Navigate to the Ganache transactions tab and locate the transaction.\n",
    "    # * Click the transaction and take a screenshot of it.\n",
    "    # Save this screenshot to the README.md file of your GitHub repository for\n",
    "    #  this Challenge assignment.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:pyvizenv] *",
   "language": "python",
   "name": "conda-env-pyvizenv-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
